/**
 * Writes src/lib/markPaths.ts: the hero's outlines as SVG path data, so the
 * flat mark (nav, favicon, no-WebGL fallback) never imports three.js.
 *   npx tsx scripts/build-mark.ts
 */
import { writeFileSync } from "node:fs";
import { bodyShape, flapShape, svgPathOf, tileShape } from "../src/lib/shapes";

const SIZE = 100;
const out = `// Generated by scripts/build-mark.ts — do not edit. Same outlines as the 3D hero.
export const MARK_SIZE = ${SIZE};
export const TILE_PATH = ${JSON.stringify(svgPathOf(tileShape(), SIZE))};
export const BODY_PATH = ${JSON.stringify(svgPathOf(bodyShape(), SIZE))};
export const FLAP_PATH = ${JSON.stringify(svgPathOf(flapShape(), SIZE))};
`;
writeFileSync(new URL("../src/lib/markPaths.ts", import.meta.url), out);
console.log("wrote src/lib/markPaths.ts");
